<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('employee_details')->insert([
            'employe_name'=>'siraj',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>2,
            'user_id'=>1
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'rahim',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>1,
            'user_id'=>2
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'paul',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>1,
            'user_id'=>3
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'tonmoy',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>2,
            'user_id'=>4
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'soikot',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>1,
            'user_id'=>5
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'orko',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'leave',
            'joining_date'=>'2022-04-04',
            'tp_id'=>2,
            'user_id'=>6
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'safi',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'leave',
            'joining_date'=>'2022-04-04',
            'tp_id'=>1,
            'user_id'=>7
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'ahnaf',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>1,
            'user_id'=>8
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'nadim',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>3,
            'user_id'=>9
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'juunim',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'leave',
            'joining_date'=>'2022-04-04',
            'tp_id'=>3,
            'user_id'=>10
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'emon',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>3,
            'user_id'=>11
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'foysal',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>1,
            'user_id'=>12
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'sifat',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>1,
            'user_id'=>13
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'tamil',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>3,
            'user_id'=>14
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'tanvir',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>3,
            'user_id'=>15
        ]);
        DB::table('employee_details')->insert([
            'employe_name'=>'valona',
            'dob'=>'1999-06-06',
            'sallary'=>6000,
            'rank'=>'sgt',
            'appoinment'=>'null',
            "status"=>'running',
            'joining_date'=>'2022-04-04',
            'tp_id'=>3,
            'user_id'=>16
        ]);
    }
}
